server:
  port: 55000

ams:
  feature-stream-engine:
    config-dir: "config"
    flow-list-path: "config/flow.list"
    bootstrap-servers: "localhost:19092"
    group-id: "ams-feature-stream-engine"
    max-poll-records: 20
    exclude-from-features: "uuid,dt,cust_id,acct_nbr,counter_acct_nbr,tx_tp,wd_or_dp"
    ml-api:
      base-url: "http://localhost:34580"
      context-path: "predict"

spring:
  datasource:
    hikari:
      goldilocks:
        max-allowed-packet: 200MB
        driver-class-name: com.singlestore.jdbc.Driver
        jdbc-url: jdbc:singlestore://localhost:3306/ams?rewriteBatchedStatements=true
        username: root
        password: 1234
      singlestore:
        max-allowed-packet: 500MB
        driver-class-name: com.singlestore.jdbc.Driver
        jdbc-url: jdbc:singlestore://localhost:3306/ams?rewriteBatchedStatements=true
        username: root
        password: 1234

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show_sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: true